link_list: ['arm_left_1_link',
            'arm_left_2_link',
            'arm_left_3_link',
            'arm_left_4_link',
            'arm_left_5_link',
            'arm_left_6_link',
            'arm_left_7_link',
            'arm_right_1_link',
            'arm_right_2_link',
            'arm_right_3_link',
            'arm_right_4_link',
            'arm_right_5_link',
            'arm_right_6_link',
            'arm_right_7_link',
            'base_sonar_01_link',
            'base_sonar_02_link',
            'base_sonar_03_link',
            'wheel_right_link',
            'wheel_left_link',
            'base_laser_link',
            'cee_right_tool_link',
            'cee_left_tool_link',]
padding: 0.05
